<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [155]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
A   = [[1,3,4],
             [2,5,7],
             [5,9,6]]

B   = [[1,0,0],
             [0,1,0],
             [0,0,1]]
A1   = [[1,2],
             [3,4]]
B1   = [[1, 4],
             [5,6],
             [7,8],
             [9, 6]]
# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    x=[]
    for i in range(len(A[1])):
        row=[]
        for j in range(len(B[0])):
            row.append(0)
        x.append(row)
    if len(A[0])==len(B):
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(B)):
                    x[i][j]+=A[i][j]*B[k][j]
        for p in x:
            print(p)
    if len(A[0])!=len(B):
        print('not possible')
    
matrix_mul(A, B)
matrix_mul(A1, B1)

[1, 3, 4]
[2, 5, 7]
[5, 9, 6]
not possible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [156]:
from random import uniform
A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]

# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    s = 0
    A=sorted(A)

    for i in range(len(A)):
        s+=A[i]
    A_norm = []
    for i in range(len(A)):
        b=A[i]/s
        A_norm.append(b)
    #print(A_norm)
    cum_sum=[]
    s1=0
    for i in range(len(A)):
        s1=s1+A_norm[i]
        cum_sum.append(s1)
    #cum_sum=sorted(cum_sum)
    #print(cum_sum)
    value = uniform(0.0,1.0)
    t=0 
    for y in range(len(cum_sum)):
        if value<= cum_sum[y] :
            t=cum_sum[y]
            break
    return A[y]
    
    


    #return #selected_random_number
A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
def sampling_based_on_magnitued():
    list1=[]
    for i in range(100):
        number= pick_a_number_from_list(A)
        list1.append(number)
    for i in range(len(A)):
        print('{} sected {} times'.format(A[i],list1.count(A[i])))


sampling_based_on_magnitued()

0 sected 0 times
5 sected 1 times
27 sected 6 times
6 sected 3 times
13 sected 1 times
28 sected 13 times
100 sected 40 times
45 sected 13 times
10 sected 1 times
79 sected 22 times


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [157]:
import re
A='a2b3c4'
def replace_digits(String):
    new=''.join(filter(str.isdigit,A))
    new1=''
    for j in new:
        new1+='#'
    new2=new1
    return new2
replace_digits(A)

'###'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [158]:

students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

def display_dash_board(students, marks):
    x=dict( zip( students, marks))
    p=sorted(x.items(), key = lambda x : x[1]) #increasing order
    p1=sorted(x.items(),key=lambda x:x[1],reverse=True) #desreasing order
    top_5_students = []
    for i in range (0,5):
        top_5_students.append(p1[i])
    #print(top_5_students)
    least_5_students = []
    for i in range(0,5):
        least_5_students.append(p[i])
    #print(least_5_students)
    percentile=[]
    for i in range(len(p)):
        percentile.append((p.index(p[i])/len(p))*100)

    students_within_25_and_75 = []
    for i in range(len(p)):
        if percentile[i]>25 and percentile[i]<=75:
            students_within_25_and_75.append(p[i])
            
            
    
    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(top_5_students)
print(least_5_students)
print(students_within_25_and_75)


[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
[('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45)]
[('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48), ('student2', 78)]


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [159]:
import math

def closest_points_to_p(S, P):
    s_sqt=[]
    sum1=0
    for i in range(len(s)):
        sum1=math.sqrt((s[i][0])**2+(s[i][1])**2)
        s_sqt.append(sum1)    
    p_sqt=math.sqrt((p[0])**2+(p[1])**2)
    distances=[]
    for i in range(len(s)):
        sum1=0
        for j in range(len(p)):
            sum1+=s[i][j]*p[j]
        v=math.acos(sum1/(s_sqt[i]*p_sqt))
        distances.append(v)
    d=dict( zip( s, distances))
    d1=sorted(d.items(), key = lambda x : x[1])
    t=[]
    for i in range(5):
        t.append(d1[i][0])
    #print(distances)
    
    return t  # its list of tuples

s=[(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
p=(3,-4)
        
points = closest_points_to_p(s, p)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [160]:
import math

def i_am_the_one(red,blue,line):
    #separating coefficients of lines as list, and elements are in string format
    line=[]
    for i in lines:
        z = re.findall('[\d\.\-\+]+', i)
        line.append(z)
    #converting line elements from string to float.
    line_c=[]
    for i in  range(len(line)):
        tr=[]
    
        for j in range(3):       
            tr.append(float(line[i][j]))
        
        line_c.append(tr) # line coefficients
    red_sqrt=[]
    sum1=0
    for i in range(len(red)):
        sum1=math.sqrt((red[i][0])**2+(red[i][1])**2)
        red_sqrt.append(sum1)
    blue_sqrt=[]
    sum2=0
    for i in range(len(blue)):
        sum2=math.sqrt((blue[i][0])**2+(blue[i][1])**2)
        blue_sqrt.append(sum2)
# finding euclidian distances of different classes from lines   
    distance_red1=[]
    distance_blue1=[]
    for i in range(len(line_c)):
        distance_red=[]
        for j in range(len(red)):
            dis_r=((line_c[i][0]*red[j][0])+(line_c[i][1]*red[j][1])+line_c[i][2])/red_sqrt[j]
            distance_red.append(dis_r)
        distance_red1.append(distance_red)
        
        distance_blue=[]
        for k in range(len(blue)):
            dis_r1=((line_c[i][0]*blue[k][0])+(line_c[i][1]*blue[k][1])+line_c[i][2])/blue_sqrt[k]
            distance_blue.append(dis_r1)
        distance_blue1.append(distance_blue)
    result=[]
    for i in range(len(line_c)):
        if (((min(distance_red1[i])>0 and max(distance_red1[i]))>0) and (min(distance_blue1[i])<0 and max(distance_blue1[i])<0)) or (((min(distance_red1[i])<0 and max(distance_red1[i])<0)) and (min(distance_blue1[i])>0 and max(distance_blue1[i])>0)):
            x='yes'
            result.append(x)
        else:
            x='no'
            result.append(x)
    return result

red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

Result=i_am_the_one(red,blue,lines)
print(Result)

['yes', 'no', 'no', 'yes']


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [1]:
def curve_smoothing(string):
    x=string.split(',')
    index=0
    position=0
    if x[0]!='_' and x[len(x)-1]=='_':
        strt=x[0]
        for n in range(len(x)):
            x[n]=int(strt)/int(len(x))
        return x
    
    else:
        for i in range(len(x)):
            if x[i]=='_':
                index+=1
            else:
                for k in range(0,i+1):
                    x[k]=int(x[i])/(index+1)
                    position=i
                break

        #_ is in middle

        if (position+1)!=len(x): # this is done to solve "_,_,_,24", else error will come
            new=1

            x1=x[position]
            for l in range(position+1, len(x)):

                if x[l]!='_':
                    print()
                    new=l+1-position
                    div=int(x1)+int(x[l])
                    break


            for b in range(position, l+1):
                x[b]= div/new
                position1=b
            #  "_" at end
            strt=x[b]
            for n in range(b,len(x)):
                x[n]=int(strt)/(len(x)-b)


        return x 

S1=  "_,_,_,24"
S2= "40,_,_,_,60"
S3= "80,_,_,_,_"
S4= "_,_,30,_,_,_,50,_,_"
smoothed_values1= curve_smoothing(S1)
smoothed_values2= curve_smoothing(S2)
smoothed_values3= curve_smoothing(S3)
smoothed_values4= curve_smoothing(S4)

print(smoothed_values1)
print(smoothed_values2)
print(smoothed_values3)
print(smoothed_values4)



[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [162]:
def compute_conditional_probabilites(A):
    count_S1=0
    count_S2=0
    count_S3=0
    for i in range(len(A)):
        if A[i][1]=='S1':
            count_S1+=1
        elif A[i][1]=='S2':
            count_S2+=1
        elif A[i][1]=='S3':
            count_S3+=1
    arr1=[count_S1,count_S2,count_S3] 
    w, h = 5, 3
    arr = [[0 for x in range(w)] for y in range(h)] 
    for i in range(len(A)):
        if A[i][0]=='F1' and A[i][1]=='S1':
            arr[0][0]+=1
        if A[i][0]=='F2' and A[i][1]=='S1':
            arr[0][1]+=1
        if A[i][0]=='F3' and A[i][1]=='S1':
            arr[0][2]+=1
        if A[i][0]=='F4' and A[i][1]=='S1':
            arr[0][3]+=1
        if A[i][0]=='F5' and A[i][1]=='S1':
            arr[0][4]+=1

    for i in range(len(A)):
        if A[i][0]=='F1' and A[i][1]=='S2':
            arr[1][0]+=1
        if A[i][0]=='F2' and A[i][1]=='S2':
            arr[1][1]+=1
        if A[i][0]=='F3' and A[i][1]=='S2':
            arr[1][2]+=1
        if A[i][0]=='F4' and A[i][1]=='S2':
            arr[1][3]+=1
        if A[i][0]=='F5' and A[i][1]=='S2':
            arr[1][4]+=1

    for i in range(len(A)):
        if A[i][0]=='F1' and A[i][1]=='S3':
            arr[2][0]+=1
        if A[i][0]=='F2' and A[i][1]=='S3':
            arr[2][1]+=1
        if A[i][0]=='F3' and A[i][1]=='S3':
            arr[2][2]+=1
        if A[i][0]=='F4' and A[i][1]=='S3':
            arr[2][3]+=1
        if A[i][0]=='F5' and A[i][1]=='S3':
            arr[2][4]+=1

    #print(arr,arr1)
    col, row = 3,5
    x= [[0 for x in range(col)] for y in range(row)]


    for i in range(len(arr1)):
        for j in range(5):
            x[j][i]=arr[i][j]/arr1[i]
    return x
    
    

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

[[0.25, 0.3333333333333333, 0.0],
 [0.25, 0.3333333333333333, 0.3333333333333333],
 [0.0, 0.3333333333333333, 0.3333333333333333],
 [0.25, 0.0, 0.3333333333333333],
 [0.25, 0.0, 0.0]]

<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [163]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    s1=S1.split(' ')
    s2=S2.split(' ')
    count=0
    s=[]
    for i in range(len(s1)):
        for j in range(len(s2)):
            if s1[i]==s2[j]:
                count+=1
                s.append(s1[i])
    s_1=[]
    for l in s1:
        if l not in s:
            s_1.append(l)
    s_2=[]
    for p in s2:
        if p not in s:
            s_2.append(p)
    return count, s_1, s_2

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c)

7 ['first', 'F', '5'] ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [164]:
def log(x):
    sums1=0.0
    for i in range(1000000):
        sums1=sums1+((-1)**(i))*(((x-1)**(i+1))/(i+1))
    return sums1/2.302585092994046
def compute_log_loss(A):
    sums=0
    for i in range(len(A)):
        sums=sums+A[i][0]*log(A[i][1])+(1-A[i][0])*(log(1-A[i][1]))
        
    loss=-(1/len(A))*sums
        
    
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
